---
- name: Download AWS SecretsManager secrets and save as env files (aws-secretsmanager-get-envs.yml)
  hosts: local_machine
  gather_facts: true
  roles:
    - role: aws_login
      when: group_aws_sso_login_required | bool
  tasks:
    - name: Get secret values from AWS SecretsManager using AWS CLI
      command: >
        aws secretsmanager batch-get-secret-value
        --secret-id-list {{ secrets | map(attribute='id') | join(' ') }}
        --output json
        --query "SecretValues"
      register: secret_raw

    - name: Parse list of secret objects
      set_fact:
        secrets_objects: "{{ secret_raw.stdout | from_json }}"

    - name: Write each secret to its corresponding env file (by name)
      copy:
        dest: "{{ item.file }}"
        mode: "0600"
        content: |
          {% set secret_obj = (secrets_objects | selectattr('Name', 'equalto', item.id) | list | first) %}
          {% set secret_json = secret_obj.SecretString | from_json %}
          {% for k, v in secret_json.items() %}
          {{ k }}={{ v }}
          {% endfor %}
      loop: "{{ secrets }}"
