---
- name: Install Docker on macOS (install-docker.yml)
  hosts: local_machine
  gather_facts: true
  tasks:
    - name: Ensure Homebrew is installed
      homebrew:
        state: present

    - name: Install Docker using Homebrew
      homebrew:
        name: docker
        state: present

    - name: Install Docker Compose using Homebrew
      homebrew:
        name: docker-compose
        state: present

    - name: Ensure docker-buildx is installed
      homebrew:
        name: docker-buildx
        state: present

    - name: Prompt user to install Docker Desktop manually if automation fails
      pause:
        prompt: |
          Docker Desktop is not installed automatically by this playbook. 
          Please install it by running the following command in your terminal:

            brew install --cask docker

          If you've installed Docker Desktop in the past and want to overwrite it, you can run:

            brew reinstall --cask docker

          Or first uninstall it with:

            brew uninstall --cask docker

          After installation, you may need to start Docker Desktop manually.
          Then open Docker Desktop from Applications and complete setup.

          Press ENTER to continue after completing these steps.

    - name: Prompt user to open Docker Desktop
      pause:
        prompt: |
          Please open and configure Docker Desktop from Applications and complete the setup.

            open -a "Docker"

          Press ENTER to continue after completing these steps.
