---
- name: Install Visual Studio Code on macOS
  hosts: local_machine
  become: false
  gather_facts: true
  tasks:
    - name: Ensure Homebrew is installed
      homebrew:
        state: present
      tags: [brew, vscode]

    - name: Check if Visual Studio Code is already installed
      stat:
        path: "/Applications/Visual Studio Code.app"
      register: vscode_installed
      tags: [vscode, check]

    - name: Install Visual Studio Code using Homebrew Cask
      community.general.homebrew_cask:
        name: "{{ vscode_cask_name }}"
        state: present
      when: not vscode_installed.stat.exists
      tags: [vscode, gui]

    - name: Install VSCode extensions using code CLI
      ansible.builtin.command: code --install-extension {{ item }}
      loop: "{{ extensions }}"
      register: vscode_extension_result
      changed_when: "'already installed' not in vscode_extension_result.stdout"
      failed_when: vscode_extension_result.rc != 0 and 'already installed' not in vscode_extension_result.stdout
      tags: [vscode, extensions]
