---
- name: Install Homebrew on macOS
  hosts: local_machine
  gather_facts: true
  tasks:
    - name: Check if Homebrew is installed (any location)
      shell: command -v brew
      register: brew_check
      ignore_errors: true

    - name: Install Homebrew
      when: brew_check.rc != 0
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /opt/homebrew/bin/brew
      become: true
